## TODO
- Implementar reset y wait skills
- Saber si un articulated object esta dentro de algo o no
- Implementar planning con lenguaje natural (hwchase17/langchain)
- Poder inspeccionar escena antes de correrlo
- leer lista articulated -> query lenguaje natural -> Language model diciendo nav, pick, place
- Entendimiento fuzzy de palabras (inicialmente con gpt)
- Add debug bounding box to img video
- Affordance function con clip 
- Agregar manipulation skills/ entrenarlas
- Interactividad con pygame
- Poder hacerlo por imagenes tambien 

## TODO LATER
- Implementar condicion de success en skill
- Mejorar pick, nav, place

## Ideas
- Vacia refrigerador 
- Limpia mesa

** Darle tools sobre el simulador** 

In [1]:
from setup_experiment import setup
from pprint import pprint
import habitat
from sensors import register_sensors
import torch


conf = setup()
device = torch.device("cuda", conf.habitat_baselines.torch_gpu_id)
ppo_cfg = conf.habitat_baselines.rl.ppo
register_sensors(conf)

env = habitat.Env(config=conf)

# Initial reset
obs = env.reset()

/private/home/sergioarnaud/habitat-llm/src/setup_experiment.py:51: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  with initialize(config_path="conf"):
2022-12-18 22:34:30,262 Initializing dataset RearrangeDataset-v0


Using a generated random seed 31735059


2022-12-18 22:34:45,632 initializing sim RearrangeSim-v0
2022-12-18 22:34:48,781 Initializing task RearrangeEmptyTask-v0
Trade::AssimpImporter::material(): property $tex.uvtrafo is a float array of 20 bytes, saving as a typeless buffer
Trade::AssimpImporter::material(): property $tex.uvtrafo is a float array of 20 bytes, saving as a typeless buffer
Trade::AssimpImporter::material(): property $tex.uvtrafo is a float array of 20 bytes, saving as a typeless buffer
Trade::AssimpImporter::material(): property $tex.uvtrafo is a float array of 20 bytes, saving as a typeless buffer
Trade::AssimpImporter::material(): property $tex.uvtrafo is a float array of 20 bytes, saving as a typeless buffer
Trade::AssimpImporter::material(): property $tex.uvtrafo is a float array of 20 bytes, saving as a typeless buffer
Trade::AssimpImporter::material(): property $tex.uvtrafo is a float array of 20 bytes, saving as a typeless buffer
Trade::AssimpImporter::material(): property $tex.uvtrafo is a float array 

In [12]:
from language_agent import LanguageAgent

mappings = {
            'dynamic_goal_to_agent_gps_compass' : 'goal_to_agent_gps_compass',
            'dynamic_obj_start_sensor' : 'obj_start_sensor',
            'dynamic_obj_goal_sensor' : 'obj_goal_sensor',
        }

agent = LanguageAgent(env, conf, mappings, device)

[INFO,habitat_baselines] 2022-12-18 22:38:57,120 hierarchichal_policy.py:236 Initializing skill: pick
[DEBUG,habitat_baselines] 2022-12-18 22:38:57,158 nn_skill.py:172 Loaded obs space Dict(is_holding:Box(0.0, 1.0, (1,), float32), joint:Box(-3.4028235e+38, 3.4028235e+38, (7,), float32), obj_start_sensor:Box(-3.4028235e+38, 3.4028235e+38, (3,), float32), relative_resting_position:Box(-3.4028235e+38, 3.4028235e+38, (3,), float32), robot_head_depth:Box(0.0, 1.0, (256, 256, 1), float32)) for skill PickSkillPolicy
[DEBUG,habitat_baselines] 2022-12-18 22:38:57,158 nn_skill.py:176 Expected obs space: ['robot_head_depth', 'obj_start_sensor', 'joint', 'is_holding', 'relative_resting_position']
[DEBUG,habitat_baselines] 2022-12-18 22:38:57,159 nn_skill.py:198 Loaded action space ActionSpace(arm_action:Dict(arm_action:Box(-1.0, 1.0, (7,), float32), grip_action:Box(-1.0, 1.0, (1,), float32)), base_velocity:Dict(base_vel:Box(-20.0, 20.0, (2,), float32))) for skill PickSkillPolicy
[DEBUG,habitat_bas

In [14]:
pprint(agent.scene_parser.grouped_objects)

{'Chair': [peach [015_peach_:0000]],
 'Counter': [tuna fish can [007_tuna_fish_can_:0000],
             strawberry [012_strawberry_:0000],
             plum [018_plum_:0000],
             master chef can [002_master_chef_can_:0000],
             lemon [014_lemon_:0001],
             bowl [024_bowl_:0002],
             tomato soup can [005_tomato_soup_can_:0001],
             potted meat can [010_potted_meat_can_:0001],
             mug [025_mug_:0000]],
 'Drawer': [pear [016_pear_:0000],
            tomato soup can [005_tomato_soup_can_:0000],
            gelatin box [009_gelatin_box_:0001],
            bowl [024_bowl_:0001],
            cracker box [003_cracker_box_:0000],
            banana [011_banana_:0001],
            apple [013_apple_:0001]],
 'Fridge': [sponge [026_sponge_:0000], banana [011_banana_:0000]],
 'Sink': [gelatin box [009_gelatin_box_:0000], bowl [024_bowl_:0000]],
 'Sofa': [lemon [014_lemon_:0000],
          tuna fish can [007_tuna_fish_can_:0001],
          potted

In [17]:
agent.set_target('004_sugar_box_:0000')

The target is set to sugar box in the Table


In [18]:
agent.go()

[DEBUG,habitat_baselines] 2022-12-18 22:40:03,498 high_level.py:42 Entering skill reset_arm
[DEBUG,habitat_baselines] 2022-12-18 22:40:03,994 skill.py:62 Skill ResetArmSkill @ step tensor([27.], device='cuda:0'): Requested skill termination tensor([True], device='cuda:0')
[DEBUG,habitat_baselines] 2022-12-18 22:40:03,996 high_level.py:42 Entering skill nav
[DEBUG,habitat_baselines] 2022-12-18 22:40:04,643 skill.py:62 Skill NavSkillPolicy @ step tensor([28.], device='cuda:0'): Requested skill termination tensor([True], device='cuda:0')
[DEBUG,habitat_baselines] 2022-12-18 22:40:04,644 high_level.py:42 Entering skill reset_arm
[DEBUG,habitat_baselines] 2022-12-18 22:40:04,663 skill.py:62 Skill ResetArmSkill @ step tensor([1.], device='cuda:0'): Requested skill termination tensor([True], device='cuda:0')
[DEBUG,habitat_baselines] 2022-12-18 22:40:04,664 high_level.py:42 Entering skill pick
[DEBUG,habitat_baselines] 2022-12-18 22:40:06,127 skill.py:62 Skill PickSkillPolicy @ step tensor([6

In [46]:
import os
import imageio
writer = imageio.get_writer(
    os.path.join('jeje/', 't1.mp4'),
    fps=30,
    quality=4,
)
images_iter = imgs
for im in images_iter:
    writer.append_data(im)
writer.close()

In [ ]:
prev_actions

tensor([[ 0.7836, -0.3021,  1.0554, -0.9342,  2.1468, -0.2929,  2.6186, -1.0000,
         -0.8106,  1.5978,  0.0000]], device='cuda:0', grad_fn=<CopyBackwards>)

In [ ]:
a = [np.clip(actions.cpu()[0].detach().numpy(), -100, 100)]

In [ ]:
['goal_to_agent_gps_compass', 'joint']
dict_keys(['goal_to_agent_gps_compass', 'joint', 'robot_head_depth', 'robot_third_rgb'])

In [ ]:
actions

{'action': ('arm_action', 'base_velocity', 'rearrange_stop'),
 'action_args': {'arm_action': array([-1.1724347 ,  1.0292538 ,  0.5338475 ,  0.45561925, -1.5024108 ,
         -1.0308689 , -0.56501436], dtype=float32),
  'grip_action': array([-1.491458], dtype=float32),
  'base_vel': array([-0.07708543,  0.9953074 ], dtype=float32),
  'rearrange_stop': array([0.], dtype=float32)}}

In [ ]:
env.step([a,b])

TypeError: list indices must be integers or slices, not str

In [ ]:
e

In [ ]:
a = action_space.sample()

In [ ]:
b = action_space.sample()

{'action': 'rearrange_stop', 'action_args': None}

In [ ]:
b

{'action': 'arm_action',
 'action_args': OrderedDict([('arm_action',
               array([ 0.92944694, -0.23688163, -0.12619945,  0.10966914,  0.10090859,
                       0.87090665,  0.38779953], dtype=float32)),
              ('grip_action', array([-0.46496338], dtype=float32))])}

In [ ]:
envs.step(a)

NameError: name 'a' is not defined

In [ ]:
envs

NameError: name 'envs' is not defined

In [ ]:
step_data

NameError: name 'step_data' is not defined

In [ ]:
hidden_states

tensor([[[-0.0961,  0.0022, -0.0592,  ...,  0.1967,  0.2684,  0.0395],
         [ 0.1866, -0.0981, -0.2612,  ..., -0.1694,  0.0365,  0.0268],
         [-0.1526,  0.0057, -0.0819,  ...,  0.7220,  0.2926,  0.0701],
         [ 0.2475, -0.1863, -0.4512,  ..., -0.3055,  0.0788,  0.0534]]],
       device='cuda:0', grad_fn=<PermuteBackward0>)

In [ ]:
%xmode

Exception reporting mode: Verbose


In [ ]:
not_done_masks

tensor([[False]], device='cuda:0')

AttributeError: 'str' object has no attribute 'items'

In [ ]:
import torch
from habitat_baselines.common.baseline_registry import baseline_registry

In [ ]:
try:
    ckpt_dict = torch.load(
        config.load_ckpt_file, map_location="cpu"
    )
except FileNotFoundError as e:
    raise FileNotFoundError(
        "Could not load neural network weights for skill."
    ) from e

policy_cfg = ckpt_dict["config"]
policy = baseline_registry.get_policy(config.name)

expected_obs_space = policy_cfg.habitat.gym.obs_keys
excepted_action_space = policy_cfg.habitat.task.actions.keys()

b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,467]:
Bad inertia tensor properties, setting inertia to zero for link: r_gripper_finger_link
b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,467]:
Bad inertia tensor properties, setting inertia to zero for link: l_gripper_finger_link
b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,467]:
Bad inertia tensor properties, setting inertia to zero for link: r_gripper_finger_link
b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,467]:
Bad inertia tensor properties, setting inertia to zero for link: l_gripper_finger_link


AttributeError: 'RearrangeSim' object has no attribute 'dynamic_target'

{'robot_head_rgb': array([[[231, 229, 227],
         [231, 230, 228],
         [232, 231, 228],
         ...,
         [ 23, 138, 209],
         [ 25, 140, 211],
         [ 27, 141, 212]],
 
        [[231, 228, 225],
         [232, 230, 227],
         [232, 231, 228],
         ...,
         [ 23, 132, 201],
         [ 26, 134, 201],
         [ 23, 133, 202]],
 
        [[231, 228, 226],
         [232, 229, 227],
         [232, 232, 230],
         ...,
         [ 23, 128, 193],
         [ 23, 131, 198],
         [ 21, 124, 188]],
 
        ...,
 
        [[112,  97,  60],
         [111,  96,  57],
         [108,  92,  53],
         ...,
         [ 77,  81,  88],
         [ 78,  81,  88],
         [ 78,  81,  88]],
 
        [[110,  95,  56],
         [105,  90,  50],
         [107,  91,  51],
         ...,
         [ 78,  81,  88],
         [ 78,  81,  88],
         [ 78,  81,  88]],
 
        [[106,  90,  51],
         [106,  90,  50],
         [108,  91,  52],
         ...,
         [

In [ ]:
env.sim.ep_info

{'episode_id': '1573', 'scene_id': 'data/replica_cad/configs/scenes/v3_sc2_staging_14.scene_instance.json', 'scene_dataset_config': 'data/replica_cad/replicaCAD.scene_dataset_config.json', 'additional_obj_config_paths': ['data/objects/ycb/'], 'start_position': [0, 0, 0], 'start_rotation': [0, 0, 0, 1], 'info': {'object_labels': {'008_pudding_box_:0000': 'hab2|0'}}, '_shortest_path_cache': None, 'ao_states': {'fridge_:0000': {'2': 0.0}, 'kitchen_counter_:0000': {'1': 0.0, '2': 0.0, '3': 0.0, '4': 0.0, '5': 0.0, '6': 0.0, '7': 0.5}}, 'rigid_objs': [['008_pudding_box.object_config.json', [[0.95316, 0.01236, -0.3022, -1.77234], [-0.00576, 0.99972, 0.02274, 0.5072], [0.3024, -0.01993, 0.95297, 0.32506], [0.0, 0.0, 0.0, 1.0]]], ['003_cracker_box.object_config.json', [[-0.68914, 0.01388, -0.7245, -2.19572], [0.0231, 0.99973, -0.00282, 0.4936], [0.72426, -0.01868, -0.68927, 1.2256], [0.0, 0.0, 0.0, 1.0]]], ['024_bowl.object_config.json', [[-0.85755, 0.00164, 0.5144, -2.35596], [0.0014, 1.0, -0

In [ ]:
# Why no cambiaron?
env._sim._sensors

{'robot_head_rgb': <habitat_sim.simulator.Sensor at 0x7fa0d1e2df10>,
 'robot_head_depth': <habitat_sim.simulator.Sensor at 0x7fa0d1e2dcd0>,
 'robot_arm_rgb': <habitat_sim.simulator.Sensor at 0x7fa0d1a6da90>,
 'robot_arm_depth': <habitat_sim.simulator.Sensor at 0x7fa10a742490>}

In [ ]:
env._sim.ep_info['rigid_objs'][2]

['005_tomato_soup_can.object_config.json', [[-0.89562, 0.00583, 0.44479, 0.52849], [0.00491, 0.99998, -0.00322, 0.53788], [-0.4448, -0.0007, -0.89563, 5.72775], [0.0, 0.0, 0.0, 1.0]]]

In [ ]:
env

{'ELECTRON_RUN_AS_NODE': '1',
 'USER': 'sergioarnaud',
 'MallocNanoZone': '0',
 '__CFBundleIdentifier': 'com.microsoft.VSCode',
 'COMMAND_MODE': 'unix2003',
 'LOGNAME': 'sergioarnaud',
 'PATH': '/Users/sergioarnaud/miniconda/envs/habitat-llm/bin:/Users/sergioarnaud/miniconda/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/CPE/bin/FBSKSAgent.app/Contents/MacOS:/opt/facebook/bin:/opt/facebook/bin/biggrep:/opt/facebook/nix/bin:/opt/facebook/ops/scripts/chef:/opt/homebrew/bin:/usr/local/munki:/opt/facebook/hg/bin',
 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.2fHRiAjf61/Listeners',
 'SHELL': '/bin/zsh',
 'HOME': '/Users/sergioarnaud',
 '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0',
 'TMPDIR': '/var/folders/6j/6qtm9y3d4c3086pvl_w3ps200000gn/T/',
 'XPC_SERVICE_NAME': '0',
 'XPC_FLAGS': '0x0',
 'ORIGINAL_XDG_CURRENT_DESKTOP': 'undefined',
 'VSCODE_CWD': '/',
 'VSCODE_NLS_CONFIG': '{"locale":"en-us","availableLanguages":{},"_languagePackSupport":true}',
 'VSCODE_CODE_CACHE_PAT